spring:
  application:
    name: BcaFinalYearProject
  profiles:
    active: prod
    servlet:
      multipart:
        max-file-size: 50MB
  springdoc:
    default-produces-media-type: application/json
